name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - name: Test
        run: cargo test --verbose
      - name: Notify
        run: cargo run --example run -- --release
        env:
          APIALERTS_API_KEY: ${{ secrets.APIALERTS_API_KEY }}
