name: Publish to crates.io

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --verbose
      - name: Publish to crates.io
        run: cargo publish --token ${{ secrets.CRATES_REGISTRY_TOKEN }}
      - name: Notify
        run: cargo run --example run -- --publish
        env:
          APIALERTS_API_KEY: ${{ secrets.APIALERTS_API_KEY }}
