name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Lint
        run: |
          cargo fmt --check
          cargo clippy --all-targets -- -D warnings
      - name: Test
        run: cargo test --verbose
      - name: Notify
        run: cargo run --example run -- --build
        env:
          APIALERTS_API_KEY: ${{ secrets.APIALERTS_API_KEY }}
